<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ASHCHOUD-LAP" ignored="0" name="Test" tests="1" failures="1" timestamp="06 Feb 2018 11:12:12 GMT" time="136.036" errors="0">
  <testcase name="feature" time="132.479" classname="cucumber.api.testng.AbstractTestNGCucumberTests">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: User got logged in so failing this step.. expected [true] but found [false]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: User got logged in so failing this step.. expected [true] but found [false]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
Caused by: java.lang.AssertionError: User got logged in so failing this step.. expected [true] but found [false]
	at stepDefinitions.LoginStepDefinitions.user_didnot_log_in_successfully(LoginStepDefinitions.java:65)
	at âœ½.Then User did not log in successfully(features/Login.feature:8)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Test -->
